# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'emerge' do

pod 'SlackTextViewController'
pod 'SocketRocket'
pod 'PureLayout'
pod 'LoremIpsum'
pod 'HIPLocationManager', :git => 'https://github.com/Hipo/HIPLocationManager.git'
pod 'ReactiveCocoa'

end
